dependencies:
  - role: download
    file: "{{ downloads.netcheck_server }}"
    when: deploy_netchecker
    tags: [download, netchecker]
  - role: download
    file: "{{ downloads.netcheck_agent }}"
    when: deploy_netchecker
    tags: [download, netchecker]
  - {role: kubernetes-apps/ansible, tags: apps}
  - role: kubernetes-apps/influxdata
    when: influx_enabled
    tags: [ apps, influxdata ]
  - role: kubernetes-apps/thunderstruck
    when: thunderstruck_enabled
    tags: [ apps, thunderstruck ]
