---
- hosts: all
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles: 
    - { role: docker-swarm, tags: docker}
    - { role: swarm, tags: swarm }

- hosts: localhost
  gather_facts: False
  roles:
   - { role: build-container, sudo: yes, thunderstruckconfig_build: true, thunderstruck_build: true} 

- hosts: all
  roles: 
   - { role: monitoring-swarm, tags: monitoring }
   - { role: swarm-apps/thunderstruck-config, tags: thunderstruck-config }
   - { role: swarm-apps/thunderstruck, tags: thunderstruck }
   - { role: generate-graph, tags: graph-grafana }
