---
- hosts: localhost
  gather_facts: False
  roles:
   - { role: build-container, sudo: yes}
   - { role: bastion-ssh-config } 

- hosts: all
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles: 
    - { role: docker, tags: docker}
    - { role: monitoring, tags: monitoring }
    - { role: swarm, tags: swarm }

- hosts: master1
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: swarm-apps/thunderstruck, tags: thunderstruck }}
    - { role: swarm-apps/thunderstruck-config, tags: thunderstruck }
