---
- name: copy tar of sogeti containers in all host
  file: 
    src: "{{ role_dir }}/../../build_container/files/{{ item }}.tar.gz"
    dest: "/tmp/{{ item }}.tar.gz"
  with_items:
    - thunderstruck-config

- name: load sogeti images
  docker_image: 
    name: sogeti/thunderstruck-config
    tag: 1.0
    load_path: "/tmp/{{ item}}.tar.gz"
  with_items:
     - thunderstruck-config

- name: launch thunderstruck-config/mongodb service
  kube:
    name: "thunderstruck-config-service"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/thunderstruck-config-service.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent

- name: launch thunderstruck-config/mongodb controller
  kube:
    name: "thunderstruck-controller"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/thunderstruck-config-controller.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent
