---
- name: copy configuration file for influxdb 
  copy: 
    src: "configuration.j2"
    dest: "~/relay.toml"

- name: edit copy templates influxdb
  template:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
  with_items: 
    - { source: "grafana-service.yaml", destination: "{{ kube_config_dir }}/grafana-service.yaml" }
    - { source: "heapster-controller.yaml", destination: "{{ kube_config_dir }}/heapster-controller.yaml" }
    - { source: "heapster-service.yaml", destination: "{{ kube_config_dir }}/heapster-service.yaml" }
    - { source: "influxdb-grafana-controller.yaml", destination: "{{ kube_config_dir }}/influxdb-grafana-controller.yaml" }
    - { source: "influxdb-service.yaml", destination: "{{ kube_config_dir }}/influxdb-service.yaml" }


- name: launch relay
  kube:
    name: "heapster-service"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/heapster-service.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent

- name: launch relay
  kube:
    name: "heapster-controller"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/heapster-controller.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent


- name: launch relay
  kube:
    name: "influxdb-service"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/influxdb-service.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent

- name: launch relay
  kube:
    name: "grafana-service"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/grafana-service.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent 

- name: launch relay
  kube:
    name: "influxdb-grafana-controller"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/influxdb-grafana-controller.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent
