---
- name: create conf dir for grafana
  file:
    path: /data/grafana/config
    state: directory

- name: create data dir for grafana
  file:
    path: /data/grafana/data
    state: directory

- name: create conf dir for influxdb
  file:
    path: /data/influxdb/config
    state: directory

- name: create data dir for influxdb
  file:
    path: /data/influxdb/data
    state: directory

- name: Launch multiples influxdb instances
  include: launch_influxdb.yml outer_item="{{ db_name }}"
  with_items: 
    - "prevision"
    - "mesure"
    - "anomalie"
    - "other"
  loop_control: 
    loop_var: db_name

- name: Launch grafana instance 
  include: launch_grafana.yml
  delegate_to: node1
