---
- name: copy configuration file for influxdb 
  copy: 
    src: "configuration.j2"
    dest: "~/relay.toml"

- name: edit copy templates influxdb
  template:
    src: "{{ item.source }}"
    dest: "{{ item.destination }}"
  with_items: 
    - { source: "influxdb-grafana-rc.yaml", destination: "{{ kube_config_dir }}/influxdb-grafana-rc.yaml" }
    - { source: "influxdb-peers-rc.yaml", destination: "{{ kube_config_dir }}/influxdb-peers-rc.yaml" }
    - { source: "influxdb-svc.yaml", destination: "{{ kube_config_dir }}/influxdb-svc.yaml" }
    - { source: "telegraf-rc.yaml", destination: "{{ kube_config_dir }}/telegraf-rc.yaml" }
    - { source: "influxdb-grafana-svc.yaml", destination: "{{ kube_config_dir }}/influxdb-grafana-svc.yaml" }
    - { source: "influxdb-raft-rc.yaml", destination: "{{ kube_config_dir }}/influxdb-raft-rc.yaml" }
    - { source: "infra-namespace.yaml", destination: "{{ kube_config_dir }}/infra-namespace.yaml" }


- name: launch relay
  kube:
    name: "influxdb-svc"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/influxdb-svc.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent

- name: launch relay
  kube:
    name: "influxdb-raft-rc"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/influxdb-raft-rc.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent

- name: launch relay
  kube:
    name: "influxdb-peers-rc"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/influxdb-peers-rc.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent

- name: launch relay
  kube:
    name: "telegraf-rc"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/telegraf-rc.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent

- name: launch relay
  kube:
    name: "influxdb-grafana-svc"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/influxdb-grafana-svc.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent

- name: launch relay
  kube:
    name: "influxdb-grafana-rc"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/influxdb-grafana-rc.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent 
