---
- name: Launch multiples instance of bdd influxdb
  include: launcher.yml outer_item="{{ db_name }}"
  with_items: 
    - "prevision"
    - "mesure"
    - "anomalie"
    - "other"
  loop_control: 
    loop_var: db_name
