apiVersion: v1
kind: Service
metadata:
  name: Thunderstruck
  namespace: kube-system
  labels: 
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
    kubernetes.io/name: "thunderstruck"
spec: 
  ports: 
    - name: api-1
      port: 27017
      targetPort: 27017
    - name: api-2 
      port: 3000
      targetPort: 3000
  selector: 
    k8s-app: InfluxDb
