---
- name: launch container1 images in swarm 
  command: docker service create --mode=global sogeti/container1

- name: launch container2 images in swarm
  command: docker service create --mode=global sogeti/container2

- name: launch container3 image in swarm 
  command: docker service create --mode=global sogeti/container3

- name: launch infludb 
  command: "docker service create --mode=global -p 8076:8086 -p 8073:8083 -v {{ sto_path}}/influxdb:/var/lib/influxdb influxdb:1.3"

- name: create directory for persistent storage grafana
  file: 
    path: "{{ sto_path }}"/grafana
    state: directory
    mode: 0755

- name: launch persistent storage grafana
  docker_container: 
    name: grafana-sto
    image: busybox:1.27
    volumes: "{{ sto_path }}/grafana" 

- name: launch grafana for thunderstruck
  docker_container:
     name: grafana
     image: grafana/grafana:4.4.1
     volumes-from: grafana-sto
     exposed_ports:
       - 2000:3000 
  
