---
- name: chargement image base_container en local repository
  docker_image:
    name: thunderstruck
    tag: v1
    push: yes
    load_path: "{{ base_container }}"

- name: chargement image thunderstruck en local repository
  docker_image:
    name: thunderstruck-config
    tag: v1
    push: yes
    load_path: "{{ thunderstruck-config }}"

- name: launch thunderstruck images1 in swarm 
  command: docker run 

- name: launch thunderstruck images2 in swarm
  command: docker 
