---
- stat: path="{{ container_conf }}/thunderstruck-config.tar.gz"
  register: thunderstruckconfig

- name: deploy thunderstruck config images
  copy: 
     src: ../../../build-container/files/thunderstruck-config.tar.gz
     dest: "{{ container_conf }}/thunderstruck-conf.tar.gz"
  when: thunderstruckconfig.stat.exists == False
  tags: thunderstruck

- name: chargement image thunderstruck en local repository
  docker_image:
    name: thunderstruck-config
    tag: 1.0
    push: yes
    load_path: "{{ container_conf }}/thunderstruck-conf.tar.gz"

