---
- stat: path="{{ container_conf }}/thunderstruck-config.tar.gz"
  register: thunderstruck-config

- name: deploy thunderstruck config images
  copy: 
     src: ../../../build-container/files/thunderstruck-config.tar.gz
     dest: "{{ container_conf }}/thunderstruck-conf.tar.gz"
  when: thunderstruck-config.stat.exists == True
  tags: thunderstruck

- name: chargement image thunderstruck en local repository
  docker_image:
    name: thunderstruck-config
    tag: v1
    push: yes
    load_path: "{{ thunderstruck-config }}"

