---
- name: Get list of labels
  command: >-
         docker inspect
         --format {% raw %}'{{range $key, $value := .Spec.Labels}}{{printf "%s\n" $key}}{{end}}'{% endraw %}
         {{ ansible_hostname }}
  register: docker_swarm_labels
  changed_when: False
  delegate_to: "{{ groups['swarm-manager'][0]}}"
  delegate_facts: True
  tags:
    - skip_ansible_lint
    - swarm_labels

- name: Remove labels from swarm node
  command: docker node update --label-rm {{ item }} {{ ansible_hostname }}
  with_items: "{{ docker_swarm_labels.stdout_lines }}"
  when: "{{ docker_swarm_labels.stdout_lines | count > 0 }}"
  changed_when: False
  delegate_to: "{{ groups['swarm-manager'][0] }}"
  delegate_facts: True
  tags:
    - skip_ansible_lint
    - swarm_labels

- name: Asign labels to swarm nodes | if any
  command: docker node update --label-add {{ item }}=true {{ ansible_hostname }}
  changed_when: False
  with_items:
    - "manager"
  delegate_to: "{{ groups['swarm-manager'][0] }}"
  delegate_facts: True
  tags:
    - skip_ansible_lint
    - swarm_labels

