---
# Check that a page returns a status 200 and fail if the word AWESOME is not
# in the page contents.
#
#
- name: Wait for stack to be run
  pause: 
    seconds: 15

#InfluxdbMonitoring 
- uri:
    url: "http://{{ hostvars['node1']['ansible_' + grafana_expose_interface]['ipv4']['address'] }}:2000/api/datasources/name/InfluxMonitoring"
    user: "admin"
    password: "{{ grafana_default_pass }}"
    force_basic_auth: yes
  register: grafana_influxdb
  failed_when: false
  changed_when: false
  when: inventory_hostname == 'node1'

- name: Enable InfluxMonitoring Datasource
  uri:
    url: "http://{{ hostvars['node1']['ansible_' + grafana_expose_interface]['ipv4']['address'] }}:2000/api/datasources"
    method: POST
    user: "admin"
    password: "{{ grafana_default_pass }}"
    body:
      name: "InfluxMonitoring"
      type: "influxdb"
      url: "http://{{ hostvars['node1']['ansible_' + docker_swarm_interface]['ipv4']['address'] }}:8076"
      access: "direct"
      isDefault: true
      database: telegraf_{{ item }}
      user: 'admin'
      passeword: 'admin'
    force_basic_auth: yes
    body_format: json
  ignore_errors: yes 
  with_items:
    - "{{ groups['all'] }}"
  when: inventory_hostname == 'node1'
