---
- name: Create docker data repository
  file:
    path: "{{ sto_path }}/docker"
    state: directory
    mode: 0755
   
- name: Install yum-utils if necessary.
  yum:
    name: yum-utils
    state: present
  when: ansible_os_family == 'RedHat'

- name: Add the YUM Docker repository.
  yum_repository:
    name: docker
    description: Docker Repository
    baseurl: "{{ docker_yum_repo }}"
    gpgkey: "{{ docker_yum_gpgkey }}"
    gpgcheck: yes

- name: Install Docker dependencies.
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ docker_dependencies }}"

- name: Install the Docker Engine.
  package:
    name: docker-engine
    state: present

- name: Add custom docker service file
  template:
    src: docker.service.j2
    dest: /usr/lib/systemd/system/docker.service
    owner: root
    group: root
    mode: 0644

- name: Enable the Docker daemon as a service and start it.
  service:
    name: docker
    state: restarted
    enabled: yes


