balStats:
  debug: True # if true print is activated 
  quants:     # define array of quants to compute on the series
    - 0.05
    - 0.10
    - 0.25
    - 0.50
    - 0.75
    - 0.80
    - 0.85
    - 0.90
    - 0.95
    - 0.99
   
