---
- name: copy tar of sogeti containers in all host
  file: 
    src: "{{ role_dir }}/../../build_container/files/{{ item }}.tar.gz"
    dest: "/tmp/{{ item }}.tar.gz"
  with_items:
    - thunderstruck

- name: load sogeti images
  docker_image: 
    name: sogeti/thunderstruck
    tag: 1.0
    load_path: "/tmp/{{ item}}.tar.gz"
  with_items:
     - thunderstruck

- name: launch thunderstruck/mongodb service
  kube:
    name: "thunderstruck-service"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/thunderstruck-service.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent

- name: launch thunderstruck/mongodb controller
  kube:
    name: "thunderstruck-controller"
    kubectl: "{{ bin_dir }}/kubectl"
    filename: "{{ kube_config_dir }}/thunderstruck-controller.yaml"
    resource: "ds"
    namespace: "{{base_namespace}}"
    state: absent
