apiVersion: v1
kind: ReplicationController
metadata:
  name: grafana-v4
  namespace: kube-system
  labels: 
    k8s-app: Grafana
    version: v4
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec: 
  replicas: 1
  selector: 
    k8s-app: Grafana
    version: v4
  template: 
    metadata: 
      labels: 
        k8s-app: Grafana
        version: v4
        kubernetes.io/cluster-service: "true"
    spec: 
      containers: 
        - image: grafana/grafana:4.3.2
          name: grafana
          env:
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
            requests:
              cpu: 100m
              memory: 100Mi
          env:
            - name: INFLUXDB_SERVICE_URL
              value: http://monitoring-influxdb:8086
            - name: GF_AUTH_BASIC_ENABLED
              value: "false"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ORG_ROLE
              value: Admin
            - name: GF_SERVER_ROOT_URL
              value: /api/v1/proxy/namespaces/kube-system/services/grafana/
          volumeMounts:
          - name: grafana-persistent-storage
            mountPath: /var
          - name: grafana-config-file
            mountPath: ~/grafanaConfig
      volumes:
      - name: grafana-persistent-storage
        hostPath:
          path: /data/grafana/data/
      - name: grafana-config-file
        hostPath:
          path: /data/grafana/config/
