apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: influxdb
  name: influxdb-peers-rc
  namespace: infra
spec:
  replicas: 3
  selector:
    app: influxdb
    type: peer
  template:
    metadata:
      labels:
        app: influxdb
        type: peer
    spec:
      containers:
      - name: influxdb
        image: supershal/influxdb:latest
        env:
        - name: NAMESPACE
          value: infra
        - name: INFLUXDB_POD_SELECTORS
          value: app=influxdb,type=raft
        - name: INFLUXDB_META_ENABLED
          value: "false"
        volumeMounts:
        - mountPath: /data
          name: influxdb-storage
        ports:
        - name: http
          containerPort: 8083
        - name: api
          containerPort: 8086
        - name: cluster
          containerPort: 8088
      volumes:
        - name: influxdb-storage
          emptyDir: {}
