apiVersion: v1
kind: Service
metadata:
  labels: null
  name: influxdb-grafana-svc
  namespace: infra
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    targetPort: 3000 
  selector:
    app: influxGrafana
