apiVersion: v1
kind: ReplicationController
metadata:
  name: Influxdb-v1.3
  namespace: kube-system
  labels: 
    k8s-app: InfluxDb
    version: v4
    kubernetes.io/cluster-service: "true"
    addonmanager.kubernetes.io/mode: Reconcile
spec: 
  replicas: 1
  selector: 
    k8s-app: InfluxDb
    version: v4
  template: 
    metadata: 
      labels: 
        k8s-app: InfluxDb
        version: v4
        kubernetes.io/cluster-service: "true"
    spec: 
      containers: 
        - image: influxdb:v1.3
          name: influxdb
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 500Mi
          ports: 
            - containerPort: 8083
            - containerPort: 8086
          volumeMounts:
          - name: influxdb-persistent-storage
            mountPath: /data
          - name: influxdb-config-file
            mountPath: ~/influxdb.conf
      volumes:
      - name: influxdb-persistent-storage
        hostPath:
          path: /data/influxdb/data/
      - name: influx-config-file 
        hostPath: 
          path: /data/influxdb/config/
