apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: producers
  name: telegraf-rc
  namespace: infra
spec:
  replicas: 1
  selector:
    app: producers
  template:
    metadata:
      labels:
        app: producers
    spec:
      containers:
      - name: telegraf
        image: bbailey/telegraf
        env:
        - name: INFLUXDB_HOST
          value: influxdb-svc